base_agent: SAC                   # Base agent.
num_steps: 3                      # Number of steps to use the model.
num_samples: 1                    # Number of parallel samples.
gamma: 0.99                       # discount factor.
lambda_: 0.9
reward_scale: 1.0                 # scale with which to multiply rewards.
exploration_steps: 0
exploration_episodes: 1
model_learn_exploration_episodes: 0
render_train: False
render_test: False
