gamma: 0.99                       # discount factor
reward_scale: 1.0                 # scale with which to multiply rewards.
num_iter: 50
exploration_steps: 0
exploration_episodes: 0
render_train: False
render_test: False
